#[general]
#import = [
#  "/home/joel/.config/alacritty/themes/themes/nightfox.toml"
#]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.85
dynamic_padding = true
  [window.padding]
  x = 5
  y = 5

[colors]
primary = { background = "0x0f0f0f"}

[cursor]
style = "Beam"

[font]
size = 11

  [font.normal]
  family = "MesloLGS Nerd Font Mono"
  style = "Regular"

  [font.bold]
  family = "MesloLGS Nerd Font Mono"
  style = "Bold"

  [font.italic]
  family = "MesloLGS Nerd Font Mono"
  style = "Italic"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"
